pipelines:
# Automated pipeline for syncing Bitbucket repository with its GitHub mirror, ensuring real-time updates across platforms
# Automated pipeline for syncing Bitbucket repository with its GitHub mirror, ensuring real-time updates across platforms.
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --mirror https://x-token-auth:"$BITBUCKET_VARIABLE"@bitbucket.org/_mpt/uplift-compro.git
          - cd uplift-compro.git